<?php
/** @var Laminas\View\Renderer\PhpRenderer $this */

/** @var \Ruga\Layout\AdminLTE\AdminLteConfig $adminLteConfig */
$adminLteConfig = \Ruga\Layout\AdminLTE\Facade\AdminLte::getFacadeInstance();

$this->headLink()->prependStylesheet('app.css');
$this->inlineScript()->prependFile('app.js');
// Google Font: Source Sans Pro
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback');
// Ionicons
$this->headLink()->prependStylesheet('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css');
// Resolve conflict in jQuery UI tooltip with Bootstrap tooltip
//$this->inlineScript()->prependScript("$.widget.bridge('uibutton', $.ui.button)");

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <base href="<?= $this->basePath(); ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <?= $this->headTitle('AdminLTE')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <? $this->headLinkAssets() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <?= $this->headStyle() ?>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Preloader -->
    <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_PRELOADER]) ?>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_NAVBAR_LINKS]) ?>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_NAVBAR_SEARCH]) ?>

            <!-- Messages Dropdown Menu -->
            <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_MESSAGES_DROPDOWN]) ?>
            
            <!-- Notifications Dropdown Menu -->
            <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_NOTIFICATIONS_DROPDOWN]) ?>
            
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#"
                   role="button">
                    <i class="fas fa-th-large"></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_BRAND_LOGO]) ?>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_SIDEBAR_USER_PANEL]) ?>

            <!-- SidebarSearch Form -->
            <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_SIDEBAR_SEARCH]) ?>
            
            <!-- Sidebar Menu -->
            <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_SIDEBAR_MENU]) ?>
            
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <?= $this->content ?>
    </div>
    <!-- /.content-wrapper -->
    
    <?= $this->partial($adminLteConfig[\Ruga\Layout\AdminLTE\AdminLteConfigKeys::LTE_PART_FOOTER]) ?>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<?= $this->inlineScript() ?>

<script type="text/javascript">

    function handleTabUrl() {
        // Open tab from url hash
        let url = document.location.toString();
        if (url.match('#')) {
            $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
        }

        // Change hash in url when tab changes
        $('.nav-tabs a').on('shown.bs.tab', function (event) {
            if (history.pushState) {
                let loc = window.location;
                loc.hash = event.target.hash
                history.pushState(null, null, loc.href);
            } else {
                window.location.hash = event.target.hash; // Polyfill for old browsers
            }
        })
    }


    // Set link in sidebar active, if page is loaded
    (function ($, window, document) {
        function openParentMenu(item)
        {
            // debugger;
            const parentLi = item.closest("li.nav-item");
            const thisA = $(parentLi[0].children.item('a'));
            thisA.addClass('active');
            
            const parentUl = item.closest('ul.nav-treeview');
            if(parentUl.length === 0) return;
            const parentUlLi = parentUl.closest("li.nav-item");
            if(parentUlLi.length === 0) return;
            // const thisA = $(parentLi[0].children.item('a'));
            // console.log('parentLi=', parentLi, 'thisA', thisA);
            if (parentUlLi.length !== 0) {
                openParentMenu(parentUlLi);
                // item.addClass('active');
                parentUlLi.addClass('menu-open');
            }
        }
        
        $(function () {
            //const server = <?//=json_encode($_SERVER)?>//;
            // console.log(server);

            handleTabUrl();
            
            let pagename = '<?=str_replace($_SERVER['REDIRECT_BASE']??dirname($_SERVER['SCRIPT_NAME']), '', $_SERVER['REQUEST_URI'])?>';
            if((pagename === '') || (pagename === '/')) pagename='index.html';
            const link = $('[data-widget="treeview"] .nav-link[href="' + pagename + '"]');
            // console.log('pagename=', pagename, 'link=', link);
            if(link.length > 0) openParentMenu(link);
        });
    }(window.jQuery, window, document));
</script>


</body>
</html>


